"""initial workspace and inventory schema

Revision ID: 70dfdacc746d
Revises: 
Create Date: 2026-10-01 16:48:43.264952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db

# revision identifiers, used by Alembic.
revision: str = '70dfdacc746d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('billing_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('trial_ends_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('channel_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('last_synced_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_accounts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'sku', name='uq_inventory_item_workspace_sku')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('legacy_backfill_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('source_signature', sa.String(length=200), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('imported_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_membership_user_workspace')
    )
    op.create_table('channel_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=True),
    sa.Column('channel_account_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('external_sku', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'channel', 'external_id', name='uq_channel_listing_identity')
    )
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.create_index('ix_channel_listings_item', ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_listings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('connector_sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel_account_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('active_count', sa.Integer(), nullable=True),
    sa.Column('delete_count', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'channel', 'run_type', 'started_at', name='uq_connector_sync_run_identity')
    )
    with op.batch_alter_table('connector_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_sync_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('profile_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_account_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_account_id', 'captured_at', name='uq_profile_observation_identity')
    )
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel_account_id', sa.Uuid(), nullable=True),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_order_id', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'channel', 'direction', 'external_order_id', name='uq_sale_identity')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('favorite_events',
    sa.Column('notification_id', sa.String(length=100), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel_listing_id', sa.Uuid(), nullable=True),
    sa.Column('item_external_id', sa.String(length=200), nullable=True),
    sa.Column('item_title', sa.String(length=500), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_listing_id'], ['channel_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('favorite_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_listing_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('favourites', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_listing_id'], ['channel_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_listing_id', 'captured_at', name='uq_listing_snapshot_identity')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_captured_at'), ['captured_at'], unique=False)

    op.create_table('market_research',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel_listing_id', sa.Uuid(), nullable=True),
    sa.Column('listing_external_id', sa.String(length=200), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('requested_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('min_cents', sa.Integer(), nullable=True),
    sa.Column('median_cents', sa.Integer(), nullable=True),
    sa.Column('max_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_listing_id'], ['channel_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.create_index('ix_market_research_listing', ['listing_external_id', 'requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_research_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_research_workspace_id'))
        batch_op.drop_index('ix_market_research_listing')

    op.drop_table('market_research')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_captured_at'))

    op.drop_table('listing_snapshots')
    with op.batch_alter_table('favorite_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_events_workspace_id'))

    op.drop_table('favorite_events')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_workspace_id'))

    op.drop_table('sales')
    op.drop_table('profile_observations')
    with op.batch_alter_table('connector_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_sync_runs_workspace_id'))

    op.drop_table('connector_sync_runs')
    with op.batch_alter_table('channel_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_listings_workspace_id'))
        batch_op.drop_index('ix_channel_listings_item')

    op.drop_table('channel_listings')
    op.drop_table('memberships')
    op.drop_table('legacy_backfill_runs')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_workspace_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_accounts_workspace_id'))

    op.drop_table('channel_accounts')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
