const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const state={me:null,view:"today",file:null,mapping:{}};
const fields=["","sku","title","category","quantity","condition","cost","price","currency","location","notes","author","isbn","publisher","edition","binding","publication_year","brand","size","colour","material","measurements"];
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function money(v,c){if(v==null)return"—";return new Intl.NumberFormat(undefined,{style:"currency",currency:c||"EUR"}).format(Number(v)/100)}
function when(v){if(!v)return"—";const d=new Date(v);return isNaN(d.getTime())?"—":d.toLocaleString()}
function csrf(){if(state.me&&state.me.csrf_token)return state.me.csrf_token;const hit=document.cookie.split("; ").find(x=>x.startsWith("reseller_csrf="));return hit?decodeURIComponent(hit.split("=")[1]):""}
function flash(msg,error){$("#flash").innerHTML=msg?'<div class="flash '+(error?"error":"")+'">'+esc(msg)+"</div>":"";if(msg)setTimeout(()=>{$("#flash").innerHTML=""},4500)}
async function api(url,opts){opts=opts||{};const headers=Object.assign({},opts.headers||{});if(opts.method&&opts.method!=="GET"&&opts.method!=="HEAD")headers["X-CSRF-Token"]=csrf();if(opts.body&&!(opts.body instanceof FormData)&&!headers["Content-Type"])headers["Content-Type"]="application/json";const r=await fetch(url,Object.assign({credentials:"same-origin"},opts,{headers:headers}));const type=r.headers.get("content-type")||"";const body=type.includes("application/json")?await r.json():await r.text();if(!r.ok)throw new Error(body&&body.detail?body.detail:(body||("HTTP "+r.status)));return body}
function metric(label,value,sub){return '<article class="card metric"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong>'+(sub?'<div class="sub">'+esc(sub)+'</div>':"")+"</article>"}
function authScreen(which){$("#auth").classList.remove("hidden");$("#shell").classList.add("hidden");$("#login").classList.toggle("hidden",which==="register");$("#register").classList.toggle("hidden",which!=="register")}
function appScreen(){ $("#auth").classList.add("hidden");$("#shell").classList.remove("hidden") }
async function init(){try{state.me=await api("/api/auth/me");appScreen();$("#app-name").textContent=state.me.app_name;$("#auth-name").textContent=state.me.app_name;$("#workspace-name").textContent=state.me.workspace.name;await load("today")}catch(e){authScreen("login")}}
$("#show-register").onclick=()=>authScreen("register");$("#show-login").onclick=()=>authScreen("login");
$("#login").onsubmit=async e=>{e.preventDefault();$("#auth-error").textContent="";try{await api("/api/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await init()}catch(err){$("#auth-error").textContent=err.message}};
$("#register").onsubmit=async e=>{e.preventDefault();$("#register-error").textContent="";try{await api("/api/auth/register",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await init()}catch(err){$("#register-error").textContent=err.message}};
$("#logout").onclick=async()=>{try{await api("/api/auth/logout",{method:"POST"})}catch(e){}state.me=null;authScreen("login")};
$$(".nav").forEach(b=>b.onclick=()=>selectView(b.dataset.view));
async function selectView(view){state.view=view;$$(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$(".view").forEach(v=>v.classList.toggle("active",v.id===view));$("#page-title").textContent=$('.nav[data-view="'+view+'"]').textContent.trim();await load(view)}
async function load(view){try{if(view==="today")await today();else if(view==="inventory")await inventory();else if(view==="sales")await sales();else if(view==="analytics")await analytics();else if(view==="connections")await connections();else if(view==="settings")await settings()}catch(e){flash(e.message,true)}}
async function today(){const all=await Promise.all([api("/api/app/today"),api("/api/app/analytics")]);const t=all[0],a=all[1];$("#today-metrics").innerHTML=metric("Active inventory",a.active_inventory)+metric("Active listings",a.active_listings)+metric("Sales YTD",a.sales_ytd_count,money(a.sales_ytd_cents,a.currency))+metric("Followers",a.followers==null?"—":a.followers);$("#today-actions").innerHTML=t.actions.length?t.actions.map(x=>'<div class="action-row"><div><strong>'+esc(x.title)+'</strong><p>'+esc(x.channel)+" · "+x.age_days+" days old"+(x.favourites==null?"":" · "+x.favourites+" favourites")+'</p></div><div class="action-tag">'+esc(x.action)+"</div></div>").join(""):'<div class="empty">Nothing needs attention right now.</div>'}
async function inventory(){const q=encodeURIComponent($("#inventory-q").value.trim()),status=encodeURIComponent($("#inventory-status").value);const d=await api("/api/app/inventory?q="+q+"&status="+status);$("#inventory-table").innerHTML=d.items.length?'<table><thead><tr><th>Item</th><th>SKU</th><th>Category</th><th>Qty</th><th>Channels</th><th>Status</th></tr></thead><tbody>'+d.items.map(i=>'<tr><td><div class="title">'+esc(i.title)+'</div><div class="sub">'+esc(i.condition||"")+(i.location?" · "+esc(i.location):"")+'</div></td><td>'+esc(i.sku)+'</td><td>'+esc(i.category)+'</td><td>'+i.quantity+'</td><td>'+((i.listings||[]).map(l=>'<span class="pill '+esc(l.channel)+'">'+esc(l.channel)+"</span>").join(" ")||"—")+'</td><td>'+esc(i.status)+"</td></tr>").join("")+"</tbody></table>":'<div class="empty">No inventory yet. Add an item or import a file.</div>'}
$("#inventory-q").oninput=()=>inventory().catch(e=>flash(e.message,true));$("#inventory-status").onchange=()=>inventory().catch(e=>flash(e.message,true));$("#add-item").onclick=()=>$("#item-form").classList.remove("hidden");$("#cancel-item").onclick=()=>$("#item-form").classList.add("hidden");
$("#item-form").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.quantity=Number(d.quantity||1);try{await api("/api/app/inventory",{method:"POST",body:JSON.stringify(d)});e.currentTarget.reset();$("#item-form").classList.add("hidden");await inventory();flash("Item added.")}catch(err){flash(err.message,true)}};
async function sales(){const d=await api("/api/app/sales");$("#sales-table").innerHTML=d.sales.length?'<table><thead><tr><th>Date</th><th>Channel</th><th>Item</th><th>Direction</th><th>Status</th><th>Amount</th></tr></thead><tbody>'+d.sales.map(s=>"<tr><td>"+esc(when(s.occurred_at))+'</td><td><span class="pill '+esc(s.channel)+'">'+esc(s.channel)+"</span></td><td>"+esc(s.title||"—")+"</td><td>"+esc(s.direction)+"</td><td>"+esc(s.status||"—")+"</td><td>"+money(s.total_cents,s.currency)+"</td></tr>").join("")+"</tbody></table>":'<div class="empty">No sales recorded yet.</div>'}
async function analytics(){const a=await api("/api/app/analytics");$("#analytics-metrics").innerHTML=metric("Active inventory",a.active_inventory)+metric("Active listings",a.active_listings)+metric("Sales YTD",a.sales_ytd_count,money(a.sales_ytd_cents,a.currency))+metric("Followers",a.followers==null?"—":a.followers,a.following==null?"":a.following+" following")}
$("#preview-import").onclick=async()=>{const file=$("#import-file").files[0];if(!file)return flash("Choose a file first.",true);state.file=file;const f=new FormData();f.append("file",file);f.append("mapping_json","{}");f.append("full_snapshot",$("#full-snapshot").checked?"true":"false");try{const d=await api("/api/app/import/preview",{method:"POST",body:f});state.mapping=Object.assign({},d.suggested_mapping);renderMapping(d);renderPreview(d);$("#mapping").classList.remove("hidden");$("#preview").classList.remove("hidden");$("#import-status").textContent="Read "+d.rows+" rows from "+file.name}catch(e){flash(e.message,true)}};
function renderMapping(d){$("#mapping-grid").innerHTML=d.headers.map(h=>'<div class="map-row"><strong>'+esc(h)+'</strong><span>→</span><select data-h="'+esc(h)+'">'+fields.map(f=>'<option value="'+f+'" '+(state.mapping[h]===f?"selected":"")+'>'+(f||"Ignore")+"</option>").join("")+"</select></div>").join("");$$("#mapping-grid select").forEach(s=>s.onchange=()=>{if(s.value)state.mapping[s.dataset.h]=s.value;else delete state.mapping[s.dataset.h]})}
function renderPreview(d){const c=d.counts||{};$("#preview").innerHTML='<div class="card-head"><h2>Preview - nothing written yet</h2></div><div class="preview-stats"><span>'+(c.new||0)+' new</span><span>'+(c.update||0)+' updates</span><span>'+(c.unchanged||0)+' unchanged</span><span>'+(c.conflict||0)+' conflicts</span><span>'+(d.missing_existing_count||0)+' would archive</span></div>';$("#apply-import").disabled=!d.can_apply}
$("#apply-import").onclick=async()=>{if(!state.file)return;const f=new FormData();f.append("file",state.file);f.append("mapping_json",JSON.stringify(state.mapping));f.append("full_snapshot",$("#full-snapshot").checked?"true":"false");f.append("preset_name",$("#preset-name").value.trim());try{const r=await api("/api/app/import/apply",{method:"POST",body:f});flash("Import applied: "+r.created+" new, "+r.updated+" updated, "+r.archived+" archived.");$("#mapping").classList.add("hidden");$("#preview").classList.add("hidden")}catch(e){flash(e.message,true)}};
async function connections(){const all=await Promise.all([api("/api/app/connectors"),api("/api/app/extension/devices")]),d=all[0],devices=all[1];$("#connector-grid").innerHTML=d.connectors.map(c=>'<div class="connector"><h2>'+esc(c.display_name)+'</h2><p>'+esc(c.description)+'</p><div class="meta">'+(c.operational?"Ready":(c.configured?"Configured - setup incomplete":"Not configured"))+(c.last_synced_at?" · "+esc(when(c.last_synced_at)):"")+'</div><div class="actions">'+(c.channel==="vinted"?'<button class="btn primary pair">Pair Chrome</button>':"")+(c.sync_available?'<button class="btn sync" data-c="'+esc(c.channel)+'">Queue sync</button>':"")+"</div></div>").join("");$$(".pair").forEach(b=>b.onclick=pair);$$(".sync").forEach(b=>b.onclick=async()=>{try{await api("/api/app/connectors/"+b.dataset.c+"/sync",{method:"POST"});flash("Sync queued.")}catch(e){flash(e.message,true)}});$("#devices").innerHTML=devices.devices.length?devices.devices.map(x=>'<div class="device-row"><div><strong>'+esc(x.name)+'</strong><div class="sub">Version '+esc(x.extension_version||"unknown")+" · "+(x.last_seen_at?esc(when(x.last_seen_at)):"not seen yet")+(x.revoked?" · revoked":"")+'</div></div>'+(x.revoked?"":'<button class="btn revoke" data-id="'+x.id+'">Revoke</button>')+"</div>").join(""):'<div class="empty">No Chrome browsers paired yet.</div>';$$(".revoke").forEach(b=>b.onclick=async()=>{try{await api("/api/app/extension/devices/"+b.dataset.id,{method:"DELETE"});await connections()}catch(e){flash(e.message,true)}})}
async function pair(){try{const r=await api("/api/app/extension/pairings",{method:"POST"});$("#pair-code").textContent=r.code;$("#pairing").classList.remove("hidden")}catch(e){flash(e.message,true)}}
async function settings(){const s=await api("/api/app/settings");$("#settings-name").value=s.workspace.name;$("#billing").innerHTML=s.billing.enabled?'<p>Status: <strong>'+esc(s.billing.status)+'</strong></p><button id="billing-action" class="btn primary">'+(s.billing.customer_configured?"Manage subscription":"Choose plan")+"</button>":'<p class="muted">Billing is disabled for this installation. This is the normal local/beta configuration.</p>'+(s.security.derived_encryption_key?'<p class="muted">Configure APP_ENCRYPTION_KEY before hosting for real customers.</p>':"");const b=$("#billing-action");if(b)b.onclick=async()=>{try{const r=await api(s.billing.customer_configured?"/api/app/billing/portal":"/api/app/billing/checkout",{method:"POST"});location.href=r.url}catch(e){flash(e.message,true)}}}
$("#settings-form").onsubmit=async e=>{e.preventDefault();try{const r=await api("/api/app/settings",{method:"PATCH",body:JSON.stringify({name:$("#settings-name").value.trim()})});state.me.workspace=r.workspace;$("#workspace-name").textContent=r.workspace.name;flash("Settings saved.")}catch(err){flash(err.message,true)}};
init();